# Generated by Django 4.0.5 on 2022-07-06 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TariffSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tariff_name', models.CharField(max_length=40, null=True)),
                ('description', models.TextField(null=True)),
                ('price', models.CharField(default='600', max_length=40)),
            ],
        ),
    ]
