# Generated by Django 4.0.5 on 2022-07-06 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tariffsettings',
            old_name='tariff_name',
            new_name='name',
        ),
    ]
