# Generated by Django 4.0.5 on 2022-07-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0002_rename_tariff_name_tariffsettings_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariffsettings',
            name='level',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
