# Generated by Django 4.1 on 2022-08-28 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0033_alter_usertariff_tariff_alter_usertariff_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatingProjectFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_1', models.FileField(null=True, upload_to='files/creating_project/')),
                ('file_2', models.FileField(null=True, upload_to='files/creating_project/')),
                ('file_3', models.FileField(null=True, upload_to='files/creating_project/')),
                ('file_4', models.FileField(null=True, upload_to='files/creating_project/')),
                ('file_5', models.FileField(null=True, upload_to='files/creating_project/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner_of_creating_project', to='main.users')),
            ],
        ),
    ]
