# Generated by Django 4.1 on 2022-08-28 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creating_project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatingprojectfiles',
            name='extension_1',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='creatingprojectfiles',
            name='extension_2',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='creatingprojectfiles',
            name='extension_3',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='creatingprojectfiles',
            name='extension_4',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='creatingprojectfiles',
            name='extension_5',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
