# Generated by Django 4.1 on 2022-08-28 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creating_project', '0002_creatingprojectfiles_extension_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatingprojectfiles',
            name='file_1',
            field=models.FileField(default='', upload_to='files/creating_project/'),
        ),
        migrations.AlterField(
            model_name='creatingprojectfiles',
            name='file_2',
            field=models.FileField(default='', upload_to='files/creating_project/'),
        ),
        migrations.AlterField(
            model_name='creatingprojectfiles',
            name='file_3',
            field=models.FileField(default='', upload_to='files/creating_project/'),
        ),
        migrations.AlterField(
            model_name='creatingprojectfiles',
            name='file_4',
            field=models.FileField(default='', upload_to='files/creating_project/'),
        ),
        migrations.AlterField(
            model_name='creatingprojectfiles',
            name='file_5',
            field=models.FileField(default='', upload_to='files/creating_project/'),
        ),
    ]
