# Generated by Django 4.1 on 2022-08-29 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creating_project', '0003_alter_creatingprojectfiles_file_1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreatingProjectFiles',
        ),
    ]
