# Generated by Django 4.1 on 2022-08-31 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0038_project_file_1_project_file_2_project_file_3_and_more'),
        ('creating_project', '0004_delete_creatingprojectfiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatingProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=300)),
                ('type', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=50)),
                ('subcategory', models.CharField(max_length=50)),
                ('subsubcategory', models.CharField(max_length=60)),
                ('employee_interests', models.CharField(max_length=200)),
                ('price_no_more', models.CharField(max_length=20)),
                ('enable_price_upper', models.CharField(max_length=3)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creating_project_creator', to='main.users')),
                ('file_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creating_project_file_1', to='main.projectfiles')),
                ('file_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creating_project_file_2', to='main.projectfiles')),
                ('file_3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creating_project_file_3', to='main.projectfiles')),
                ('file_4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creating_project_file_4', to='main.projectfiles')),
                ('file_5', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creating_project_file_5', to='main.projectfiles')),
            ],
        ),
    ]
