# Generated by Django 4.1 on 2022-08-31 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creating_project', '0005_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatingproject',
            name='enable_price_upper',
            field=models.CharField(default='off', max_length=3),
        ),
    ]
