# Generated by Django 4.1 on 2022-09-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creating_project', '0008_creatingproject_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatingproject',
            name='currency',
            field=models.CharField(max_length=10),
        ),
    ]
