# Generated by Django 4.0.5 on 2022-06-13 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='name',
            new_name='name_surname',
        ),
    ]
