# Generated by Django 4.0.5 on 2022-06-13 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_name_users_name_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='date_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='desctiption',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='interests',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='name_surname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='portfolio',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='secret_key',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='subcategories',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='telegram_id',
            field=models.IntegerField(null=True),
        ),
    ]
