# Generated by Django 4.0.5 on 2022-06-13 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_secretkeys'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SecretKeys',
        ),
    ]
