# Generated by Django 4.0.5 on 2022-06-15 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_users_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='date_birth',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
