# Generated by Django 4.0.5 on 2022-06-23 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_users_date_birth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='desctiption',
            new_name='description',
        ),
    ]
