# Generated by Django 4.0.5 on 2022-06-24 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_desctiption_users_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
