# Generated by Django 4.0.5 on 2022-06-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_users_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='img',
            field=models.ImageField(upload_to='images/users'),
        ),
    ]
