# Generated by Django 4.0.5 on 2022-07-03 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_users_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='select',
            field=models.CharField(default='registration', max_length=50),
        ),
        migrations.AddField(
            model_name='users',
            name='verification',
            field=models.CharField(default='Не верефицирован', max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='status',
            field=models.CharField(default='Новичок', max_length=50),
        ),
    ]
