# Generated by Django 4.0.5 on 2022-07-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_users_select_users_verification_alter_users_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='verification',
            field=models.CharField(default='Не пройдена', max_length=50),
        ),
    ]
