# Generated by Django 4.0.5 on 2022-07-03 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetalis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=16)),
                ('card_action_date', models.CharField(max_length=5)),
                ('card_holder', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='main.users')),
            ],
        ),
    ]
