# Generated by Django 4.0.5 on 2022-07-03 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_bankdetalis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='rating',
        ),
        migrations.AddField(
            model_name='orders',
            name='feedback',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
