# Generated by Django 4.0.5 on 2022-07-03 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_orders_employee_alter_orders_employer_service_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='service',
            name='employer',
        ),
        migrations.AddField(
            model_name='service',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_user', to='main.users'),
        ),
    ]
