# Generated by Django 4.0.5 on 2022-07-04 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_service_employee_remove_service_employer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='feedback',
            new_name='feedback_to_employee',
        ),
        migrations.AddField(
            model_name='orders',
            name='feedback_to_employer',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
