# Generated by Django 4.0.5 on 2022-07-04 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_rename_feedback_orders_feedback_to_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
