# Generated by Django 4.0.5 on 2022-07-04 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_orders_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiplomsSertificats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='images/diploms_sertificats')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diploms_sertificatts_user', to='main.users')),
            ],
        ),
    ]
