# Generated by Django 4.0.5 on 2022-07-04 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_diplomssertificats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diplomssertificats',
            name='img',
            field=models.ImageField(upload_to='images/diploms_sertificats/'),
        ),
    ]
