# Generated by Django 4.0.5 on 2022-07-05 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_diplomssertificats_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='completed_on_time',
            field=models.BooleanField(null=True),
        ),
    ]
