# Generated by Django 4.0.5 on 2022-07-05 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_orders_completed_on_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
