# Generated by Django 4.0.5 on 2022-07-05 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_service_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileViews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to='main.users')),
                ('user_who_view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_who_view', to='main.users')),
            ],
        ),
    ]
