# Generated by Django 4.0.5 on 2022-07-05 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_profileviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankdetalis',
            name='status',
        ),
        migrations.AlterField(
            model_name='bankdetalis',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_holder_user', to='main.users'),
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('save_cards', models.CharField(max_length=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_settings', to='main.users')),
            ],
        ),
    ]
