# Generated by Django 4.0.5 on 2022-07-06 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_remove_bankdetalis_status_alter_bankdetalis_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TariffSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tariff_name', models.CharField(max_length=40, null=True)),
                ('description', models.TextField(null=True)),
                ('price', models.CharField(default='600', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='UserTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runs_until', models.CharField(max_length=10, null=True)),
                ('tariff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name_tariff', to='main.tariffsettings')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_tariff', to='main.users')),
            ],
        ),
    ]
