# Generated by Django 4.0.5 on 2022-07-12 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_alter_usertariff_tariff_delete_tariffsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
