# Generated by Django 4.0.5 on 2022-07-13 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0003_tariffsettings_level'),
        ('main', '0032_users_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertariff',
            name='tariff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_tariff', to='tariffs.tariffsettings'),
        ),
        migrations.AlterField(
            model_name='usertariff',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tariff', to='main.users'),
        ),
    ]
