# Generated by Django 4.1 on 2022-08-29 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_alter_usertariff_tariff_alter_usertariff_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=300)),
                ('type', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=50)),
                ('subcategory', models.CharField(max_length=50)),
                ('subsubcategory', models.CharField(max_length=60)),
                ('employee_interests', models.CharField(max_length=200)),
                ('price_no_more', models.CharField(max_length=20)),
                ('file_1', models.FileField(default='', upload_to='files/project/')),
                ('extension_1', models.CharField(max_length=10, null=True)),
                ('file_2', models.FileField(default='', upload_to='files/project/')),
                ('extension_2', models.CharField(max_length=10, null=True)),
                ('file_3', models.FileField(default='', upload_to='files/project/')),
                ('extension_3', models.CharField(max_length=10, null=True)),
                ('file_4', models.FileField(default='', upload_to='files/project/')),
                ('extension_4', models.CharField(max_length=10, null=True)),
                ('file_5', models.FileField(default='', upload_to='files/project/')),
                ('extension_5', models.CharField(max_length=10, null=True)),
                ('enable_price_upper', models.CharField(max_length=3)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_creator', to='main.users')),
            ],
        ),
    ]
