# Generated by Django 4.1 on 2022-08-29 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='extension_1',
        ),
        migrations.RemoveField(
            model_name='project',
            name='extension_2',
        ),
        migrations.RemoveField(
            model_name='project',
            name='extension_3',
        ),
        migrations.RemoveField(
            model_name='project',
            name='extension_4',
        ),
        migrations.RemoveField(
            model_name='project',
            name='extension_5',
        ),
        migrations.CreateModel(
            name='ProjectFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(default='', upload_to='files/')),
                ('extension', models.CharField(max_length=10, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_owner', to='main.users')),
            ],
        ),
    ]
