# Generated by Django 4.1 on 2022-08-29 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_alter_project_file_1_alter_project_file_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='file_1',
        ),
        migrations.RemoveField(
            model_name='project',
            name='file_2',
        ),
        migrations.RemoveField(
            model_name='project',
            name='file_3',
        ),
        migrations.RemoveField(
            model_name='project',
            name='file_4',
        ),
        migrations.RemoveField(
            model_name='project',
            name='file_5',
        ),
    ]
