# Generated by Django 4.1 on 2022-08-29 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_remove_project_file_1_remove_project_file_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='file_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_file_1', to='main.projectfiles'),
        ),
        migrations.AddField(
            model_name='project',
            name='file_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_file_2', to='main.projectfiles'),
        ),
        migrations.AddField(
            model_name='project',
            name='file_3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_file_3', to='main.projectfiles'),
        ),
        migrations.AddField(
            model_name='project',
            name='file_4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_file_4', to='main.projectfiles'),
        ),
        migrations.AddField(
            model_name='project',
            name='file_5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_file_5', to='main.projectfiles'),
        ),
    ]
