# Generated by Django 4.1 on 2022-09-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_project_file_1_project_file_2_project_file_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='currency',
            field=models.CharField(default='$', max_length=10),
        ),
    ]
