# Generated by Django 4.1 on 2022-09-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_alter_project_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='moderation',
            field=models.CharField(default='False', max_length=10),
        ),
    ]
